docs/django/django_ws_0308/articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
]

docs/django/django_ws_0308/curd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

docs/django/django_ws_0308/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

docs/django/django_ws_0308/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
# Create your views here.

def index(request):

    articles = Article.objects.order_by('-pk')
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')

docs/django/django_ws_0308/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href= {% url 'articles:new' %}>NEW</a>
  {% for article in articles %}
    <div>
      <h1>제목: {{ article.title }}</h1>
      <p>내용: {{ article.content }}</p>
    </div>
  {% endfor %}
  <a href="#">DETAIL</a>
{% endblock content %}

docs/django/django_ws_0308/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
<h1>NEW</h1>
<form action= "{% url 'articles:create' %}" method = "POST">
  {% csrf_token %}
  <label for="title">TITLE:</label>
  <input type="text" name="title" id="title"><br>
  <label for="content">CONTENT</label>
  <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
  <input type="submit" value="작성">
</form>
<a href= {% url 'articles:index' %}>BACK</a>
{% endblock content %}

docs/django/django_ws_0308/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>